#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    dpkg-trigger update-workbench
}

case "$1" in
  remove)
    remove_action
  ;;

  purge)
    remove_action
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
  ;;
esac

exit 0
